image: maven

stages:
  - build
  - test

compile:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn verify
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'