image: maven:latest

stages:
    - build
    - test

build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - echo "BUILD"
    - mvn clean compile

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - echo "TEST"
    - mvn clean test